### PR TITLE
Allows Rescheduling with one beneficiary

### PR DESCRIPTION
**Pull request by keshav0801**
Minor bugs fixed
If token is given in args, it used to skip json check, now it will fetch it if mobile number is also provided
winsound did not used to work in some Windows PC, so added playsound module as an alternative with 2 new sound files which closely resembles short and long beep of 150 and 1000 duration
fixed some layout issue
can now reschedule appointments which was much needed for some people who would prefer to have a slot nearby but don't wanna lose the one already booked far away
rescheduling api works only for 1 beneficiary, so error handling added for multiple beneficiaries

thanks @KUSHAGRA211 for sorting major technical difficulties

### CODE REVIEW

**Comment by Nakul93** [comment]
> rescheduling api works only for 1 beneficiary, so error handling added for multiple beneficiaries

Why? If the beneficiaries are booked together in the first place they would have same appointment id right, so technically they should be able to rebook using the same appointment id

**Comment by keshav0801** [comment]
I mean its for case when you try to book for more than one beneficiaries, and at least one of them has one active appointments, then the appointment cannot be really rescheduled

**Comment by Nakul93** [comment]
Ok so basically you're saying if a beneficiary has already booked and is trying to rebook with other beneficiaries who are booking for first time then this error occurs, right?

**Comment by keshav0801** [comment]
Yeah, basically you can't use BOOKING API and RESCHEDULE API at same time

**Comment by keshav0801** [comment]
unless we segregate the benefciary lists into first timers and reschedulers and make booking API calls on each of them at same time, which would make the code complicated, but I can work on that also

**Comment by keshav0801** [comment]
for the case if none of the selected benf has active appointments, the script runs as usual to the originally forked version

**Comment by Nakul93** [comment]
> unless we segregate the benefciary lists into first timers and reschedulers and make booking API calls on each of them at same time, which would make the code complicated, but I can work on that also

No let’s not make it complicated. This is fine
Will test it later

**Review by Nakul93 — APPROVED** [review]
LGTM

**Comment by keshav0801** [comment]
It would be great if this could be merged sooner because otherwise, it starts to get conflicts after every other commit on the main bombardier branch

**Pull request merged**
