### PR TITLE
Adding support to save the config file per mobile number + Handling network interruption exceptions

### PR DESCRIPTION
**Pull request by daneshqureshi**
Solving issues #139 and #141

### CODE REVIEW

**Comment by vesan83** [comment]
@daneshqureshi can you update README, how to start multiple mobile number

**Comment by daneshqureshi** [comment]
@vesan83, the script will still work for single mobile number at a time, but if you run the script for a different number as a different Python process in parallel, then it will pickup config json specific to that number.

**Comment by bombardier-gif** [comment]
LGTM. Please test this as lot of people are running the script

**Comment by daneshqureshi** [comment]
Yes tested it, I booked it for few folks in parallel

**Comment by vishalv26** [comment]
This needs more work. For eg. Captcha is gettimg saved with same name. If 2 instance is booking for same location then one instance might overwrite other instance's captcha image.

**Comment by vasugamdha** [comment]
> This needs more work. For eg. Captcha is gettimg saved with same name. If 2 instance is booking for same location then one instance might overwrite other instance's captcha image.

I have 2 points of view.

In against:
Captcha name shouldn't be an issue as that `captcha.png` is already open in the popping window. After that, the captcha of another beneficiary can replace the existing `captcha.png` file, without affecting the one already open.

In support:
Suggestion: Need to create a separate folder for every mobile number for storing captcha and JSON.

When I was booking parallelly, I created a copy of `src/` for another number. It worked for me. But technically, it's not a proper way. 

So, I suggest adding a directory for each mobile number, for sorting things out.

**Pull request merged**
