### PR TITLE
Added portable python from @vishalv26/covid-vaccine-booking

### PR DESCRIPTION
**Pull request by subho007**
This makes it easier to run in windows machine.

This PR will stay as Draft as long as I can test it out myself

### CODE REVIEW

**Comment by bombardier-gif** [comment]
Oh wow.. thats so cool @subho007 !!
I will also try to test this
Thanks a ton for this PR!

**Comment by bombardier-gif** [comment]
@subho007 let me know when this PR is well tested

**Comment by 6mxo89sqh** [comment]
@subho007 Nice one! One suggestion: Is it possible to remove the vendor files and download them on the fly during the build? If yes, we can also add the build steps in `.github/workflow/main.yaml`

**Comment by subho007** [comment]
I'll test it out by today 👍 
@6mxo89sqh absolutely ! In that case, I can put a shell script to download the files, which you can then call it via github workflow?

@bombardier-gif need your final say in this. I am running test on this by today and send this as a PR after your confirmation

**Comment by bombardier-gif** [comment]
@shailesh FYI

**Comment by shailesh** [comment]
> @shailesh FYI

will review and test this out. 
@subho007 please resolve the conflicts.

**Comment by subho007** [comment]
Will do it once I formalise the PR

**Comment by subho007** [comment]
Have checked this in Windows 7 - 10 PRO.

Added:
1. Check requirements.txt and install dependencies if required (In future if the project wants to add more dependencies)
2. Readme is updated on how to run in windows machine

Current Problems:
Huge Files are added because the Vendor itself is filled with dependencies.

Solution:
Can I zip the vendor file and use the Bat script to unzip it if not unzipped yet?

I hate to send a PR with 1K files changed 😢

**Comment by 6mxo89sqh** [comment]
@subho007 Instead of zipping and committing in repo, please download it directly in `.github/workflow/main.yaml`.

**Comment by subho007** [comment]
@6mxo89sqh but doing that will not help if someone downloads the Github zip file, unless I explicitly tell to download it from the github releases. This has it's own problem. You cannot keep creating releases if you need to test.

Or do you want me to create a bat file to download a zip file from the web and then extract?

**Comment by 6mxo89sqh** [comment]
@subho007 i am assuming that once this portable exe is created, we don't need anything else right? From user prespective, i need to go to releases and download the exe and start running that. For testing, bat file is good. 

Right now, i m not even able to see your changes, my browser hangs when i go to `Files changed` tab.

**Comment by subho007** [comment]
@6mxo89sqh I think there is a small misunderstanding here. This PR doesn't give a portable exe to run the program. What it does is:
1. Use a Portable Python Executable
2. Bat file to run the script using portable python

For the ease of review, I can say, there is not much changes, you can actually go to my fork and check it out.

1. `vendor` folder is added with portable python, and pip dependencies installed.
2. `windows.bat` file is added which keeps a check if requirement.txt needs to be installed or not followed by running the script
3. `README.md` is changed to show how to run it in windows.

I created this PR to resolve https://github.com/bombardier-gif/covid-vaccine-booking/issues/173 which talks about portable python explicitly.

Now if the expectation here is create a single `exe` binary, then we have to use pyinstaller which is already being used in the current repo, with few problems (since `pyinstaller` has problems with GUI based apps)

If this is not the correct PR which was expected, let me know.

**Comment by 6mxo89sqh** [comment]
@subh007, in that case, can we download it via `.bat` and add the vendor directory in .gitignore ?

**Comment by subho007** [comment]
That works 👍 doing the changes

**Comment by shailesh** [comment]
> Have checked this in Windows 7 - 10 PRO.
> 
> Added:
> 
> 1. Check requirements.txt and install dependencies if required (In future if the project wants to add more dependencies)
> 2. Readme is updated on how to run in windows machine
> 
> Current Problems:
> Huge Files are added because the Vendor itself is filled with dependencies.
> 
> Solution:
> Can I zip the vendor file and use the Bat script to unzip it if not unzipped yet?
> 
> I hate to send a PR with 1K files changed 😢

Adding a bat file is a good idea, have seen in other forks.

**Comment by subho007** [comment]
I can't find a way to host the Zip file, is it okay if I host it in my domain ? Seems unnecessary. If I host it in Github Releases, the Bat file which uses powershell `Invoke-Webrequest` in few places doesn't seems to download because Git has shifted to TLS1.2

This is taking way too much of my free time to work on it.

I'm thinking of keeping the PR with a Zip file in the repo itself is a good idea.

**Comment by subho007** [comment]
Well, I have pushed changes for to download/extract and update everything in a single batch script. The only problem is, natively Windows cannot download from `tls1.2` enabled HTTPS site.

I have uploaded the zip in the repo itself.

Let me know if this is a good to go, or else I have to host the file in a separate place to get it downloaded.

Please let me know if this is going to merge then I can squash the commits. This is important because

**Comment by bombardier-gif** [comment]
@6mxo89sqh  and @shailesh Is this PR good for a merge? Thoughts?

**Comment by 6mxo89sqh** [comment]
Approach wise, looks good. However, i haven't tested. This would not effect any users as it isn't touching any .py files.

**Review by shailesh — APPROVED** [review]
LGTM

**Comment by subho007** [comment]
I have added Screenshot in README, add better instructions too. I have also squashed the commits to avoid having history of 1k files.

It's good to go for me.

> Readme Review: https://github.com/subho007/covid-vaccine-booking/blob/main/README.md

**Pull request merged**
