### PR TITLE
Bug fix for #296

### PR DESCRIPTION
**Pull request by hiteshkhatri97**

### CODE REVIEW

**Comment by hiteshkhatri97** [comment]
Issue : [#296](https://github.com/bombardier-gif/covid-vaccine-booking/issues/296)

**Review by shailesh — CHANGES_REQUESTED** [review]
This won't work for another system like Mac, OS X where path has to be defined. Test it and make changes to the path of the file

**Comment by Nakul93** [comment]
> This won't work for another system like Mac, OS X where path has to be defined. Test it and make changes to the path of the file

But isn't this issue just for windows?

**Comment by hiteshkhatri97** [comment]
> > This won't work for another system like Mac, OS X where path has to be defined. Test it and make changes to the path of the file
> 
> But isn't this issue just for windows?

Yes correct this for windows only

**Review by Nakul93 — APPROVED** [review]

**Comment by shailesh** [comment]
Was the file moved from src to main or a new file was added?

**Comment by hiteshkhatri97** [comment]
PR merged but I can't see the file

**Comment by hiteshkhatri97** [comment]
> Was the file moved from src to main or a new file was added?

New file was added in main

**Pull request merged**
