### PR TITLE
Ask to cancel before rescheduling center

### PR DESCRIPTION
**Pull request by Abhinav2812**
Temporary workaround until support for rescheduling is added. Please revert once we have support. (#165)

Sample output

```
The following appointments are active! Please cancel them manually first to continue
+-------+------------------+------------------------+--------------+--------+------------+-----------------+
|   idx | beneficiary      | name                   | state_name   |   dose | date       | slot            |
+=======+==================+========================+==============+========+============+=================+
|     1 | John Doe         | P.M.C.H.               | Bihar        |      1 | 20-05-2021 | 09:00AM-11:00AM |
+-------+------------------+------------------------+--------------+--------+------------+-----------------+
|     2 | Jean Doe         | P.M.C.H.               | Bihar        |      1 | 20-05-2021 | 09:00AM-11:00AM |
+-------+------------------+------------------------+--------------+--------+------------+-----------------+
```

### CODE REVIEW

**Comment by Abhinav2812** [comment]
Disclaimer: I have not tested this for dose 2, request someone to validate this

**Comment by shailesh** [comment]
Looks good to me

**Comment by bombardier-gif** [comment]
I would suggest someone to test this first then I will merge this.

**Comment by bombardier-gif** [comment]
@Abhinav2812 What is the current behaviour which your PR is trying to fix?

**Comment by gitmnj** [comment]
@bombardier-gif ready to merge

Good Work @Abhinav2812

**Comment by gitmnj** [comment]
i personally validated with booking for dose 2

**Review by gitmnj — APPROVED** [review]

**Pull request merged**
