### PR TITLE
Revert "filtering by vaccine type #451"

### PR DESCRIPTION
**Pull request by 6mxo89sqh**
Reverts bombardier-gif/covid-vaccine-booking#453

vaccine filter is working fine as per my observation. Hence, requesting to revert the PR.

### CODE REVIEW

**Comment by 6mxo89sqh** [comment]
@warlock2k please check and confirm.

**Comment by warlock2k** [comment]
@6mxo89sqh Let me check and get back to you.

**Comment by warlock2k** [comment]
Yeah my bad, just checked, it works fine with protected APIs

**Comment by Nakul93** [comment]
Merging this since this issue occurred when using Public APIs

**Pull request merged**
