### PR TITLE
Feature/use local wifi to get otp

### PR DESCRIPTION
**Pull request by vivek43nit**
1. Added a new option to retrieve the otp from mobile. Now in python script a udp server is running which listen for  otp response from app and maintains a cache.  The app can sends the otp directly if both laptop and mobile are connected on same wifi network (magic of broadcast pkt).  For security reasons added a password option, so that in same network more than one script and app can work(needed if someone is connected to shared network).
2. refactored the code, so that it can be easily extended to more otp fetchers.

New Steps :- 

In python script :- 
After asking for mobile number, now it asks for "Please select from following option to enter OTP".
If user selects option 2, which is fetch from local wifi, then it again asks for password (same should be used in mobile).

In App Side :- 
Added a new input field named :-   Enter password (it should be same as entered after choosing option 2 in script)

Enjoy :-)

### CODE REVIEW

**Comment by vivek43nit** [comment]
Will push the code after fixing the conflict by tomorrow.

**Comment by BumpyKnuckls** [comment]
Closing it due to inactivity, please reopen after resolving merge conflicts.

**Comment by vivek43nit** [comment]
Pushed the code after resolving conflicts.

**Comment by vivek43nit** [comment]
Created new pull request after fixing conflicts.
https://github.com/bombardier-gif/covid-vaccine-booking/pull/450
@BumpyKnuckls

**Pull request closed without merging**
