### PR TITLE
Added Option to select yes-please or no in automated booking

### LINKED ISSUE #262: Option to select yes-please or no in automated booking.
Hi 
I am using this script due to auto captcha functionality. I know the slot opening time at my center and i want to manually select the center rather than yes-please command. Here centers open one by one at the interval of 10 to 15 sec. and I dont want to book first center. So please allow option to select yes-please or no for the booking. I know this defeat the purpose of automation of this script and if not possible to merge pls tell me the code to be modified in utils.py, I will modify it for my use.

Thanks

### PR DESCRIPTION
**Pull request by Nakul93**
Resolves #262

### CODE REVIEW

**Comment by bombardier-gif** [comment]
Can you please explain  the new flow?

**Comment by Nakul93** [comment]
> Can you please explain the new flow?

It will give the user an option to auto-book(random center and time slots) or manual. Default is auto book

**Comment by bombardier-gif** [comment]
And if manual.. how is the flow? I want to understand as this is in the core booking flow

**Comment by Nakul93** [comment]
> And if manual.. how is the flow? I want to understand as this is in the core booking flow

If manual you will see the table of centres and slot timings and the user can input the choice like for eg if there are 3 centres and 4 slots each. You can select something like 1.3(1st center and 3rd time slot) It’s same as the original repo from pallupz.
It’s even mentioned in our readme

**Comment by Nakul93** [comment]
This commit also fixes #280 and #281

**Pull request merged**
