### PR TITLE
Moving setup instructions to wiki

### PR DESCRIPTION
**Pull request by 6mxo89sqh**
I just wanted to move only IFTTT but while reading i realized we had duplicate setup instruction and some of them being confusing. I ended up restructuring the entire readme. 

Please review and suggest edits.

Link to review: https://github.com/6mxo89sqh/covid-vaccine-booking/blob/docs-update/README.md

#468

### CODE REVIEW

**Review by Nakul93 — COMMENTED** [review]
Did you remove the instructions for Docker?

**Comment by 6mxo89sqh** [comment]
I moved it to wiki.

**Comment by Nakul93** [comment]
> I moved it to wiki.

Yeah just saw that. You didn't update the docker run cmd to add --network="host" param. Also specify where the json file gets stored as of now I'd manually put it inside configs folder

**Comment by subho007** [comment]
in Phone setup for Android IFTT points to a non existent page

**Comment by bombardier-gif** [comment]
Thanks for improving the documentation @6mxo89sqh 
I will wait for the review comments to conclude then merge it

**Comment by 6mxo89sqh** [comment]
> > I moved it to wiki.
> 
> Yeah just saw that. You didn't update the docker run cmd to add --network="host" param. Also specify where the json file gets stored as of now I'd to put it inside configs folder manually

`--network="host"` is mandatory for AWS env only. For local it is not needed. Updated info regarding configs folder.

**Comment by 6mxo89sqh** [comment]
> Phone setup for Android IFTT points to a non existent page

Thanks! link was incorrect. Updated it.

**Comment by Nakul93** [comment]
Where does the json file gets stored when running it for first time. Where is the /app folder?
image

**Comment by 6mxo89sqh** [comment]
@Nakul93 , oh i get you now. In docker env, without specifing `--config /configs/<file_name.json>` it wont work as /app is not mounted in docker.

**Comment by Nakul93** [comment]
@6mxo89sqh so is there a way it can be saved into configs folder when running it for first time or does it need to be manually added to that folder. Idm putting it manually, if thats the only workaround then accordingly update that in wiki.

**Comment by 6mxo89sqh** [comment]
If the file name is available in the pwd's configs folder, it will be picked up.

**Comment by Nakul93** [comment]
> If the file name is available in the pwd's configs folder, it will be picked up.

Ok then could you update that in wiki.

**Comment by bombardier-gif** [comment]
Nice inputs, @6mxo89sqh Let me know when you have addressed all of those.

**Comment by 6mxo89sqh** [comment]
> > If the file name is available in the pwd's configs folder, it will be picked up.
> 
> Ok then could you update that in wiki.

Oh ya, i already updated it in wiki along with replying you earlier ;) (Check the notes section)

**Comment by shailesh** [comment]
This was needed. Good stuff @6mxo89sqh

**Comment by Nakul93** [comment]
Great work @6mxo89sqh. Wiki page was much needed.

**Review by Nakul93 — APPROVED** [review]
Great work @6mxo89sqh. Wiki page was much needed.

**Comment by 6mxo89sqh** [comment]
> This was needed. Good stuff @6mxo89sqh
> At least we will need a link pointing to each wiki page on Readme.

@shailesh this PR points to wiki. that's the change about.

**Comment by shailesh** [comment]
> > This was needed. Good stuff @6mxo89sqh
> > At least we will need a link pointing to each wiki page on Readme.
> 
> @shailesh this PR points to wiki. that's the change about.

Great reviewed now :)

**Review by shailesh — APPROVED** [review]

**Comment by bombardier-gif** [comment]
Thanks @shailesh for the review.

**Comment by shantanubharadwaj** [comment]
Where is the wiki page link? I feel the setup instruction is now in bits and pieces compared to earlier, where a layman can follow top to bottom and is ready for setup. For a technical person, it can make sense. But for a normal non-tech person, this has simply complicated everything.

**Comment by Nakul93** [comment]
The link is there in readme.

**Pull request merged**
