### PR TITLE
Fixes #308, #304, #300

### LINKED ISSUE #308: list index out of range
location_dtls:
+-------+---------------+------------------+--------------+
|   idx |   district_id | district_name    |   alert_freq |
+=======+===============+==================+==============+
|     1 |           146 | North Delhi      |         1100 |
+-------+---------------+------------------+--------------+
|     2 |           143 | North West Delhi |         1540 |
+-------+---------------+------------------+--------------+
|     3 |           150 | South West Delhi |         2420 |
+-------+---------------+------------------+--------------+
|     4 |           142 | West Delhi       |         2640 |
+-------+---------------+------------------+--------------+
        pin_code_location_dtls:
list index out of range
Exiting Script

### PR DESCRIPTION
**Pull request by 6mxo89sqh**
this pr fixes #308, #304, #300

### CODE REVIEW

**Comment by uvmittal** [comment]
thanks bro

**Comment by 6mxo89sqh** [comment]
I am testing it. plz wait for merge.

**Comment by 6mxo89sqh** [comment]
Tested. Please review and merge.

**Comment by 6mxo89sqh** [comment]
@BlackRider97 @Nakul93 @bombardier-gif @shailesh

**Comment by uvmittal** [comment]
this has been tested and can be merged successfully

**Comment by bombardier-gif** [comment]
Thanks a ton for fixing the issues.

**Pull request merged**
