### PR TITLE
[300] Fixes location search issue for option 1

### LINKED ISSUE #300: pin_code_location_dtls:
location_dtls:
+-------+---------------+-----------------+--------------+
|   idx |   district_id | district_name   |   alert_freq |
+=======+===============+=================+==============+
|     1 |           294 | BBMP            |         1100 |
+-------+---------------+-----------------+--------------+
        pin_code_location_dtls:
list index out of range
Exiting Script
sh: pause: command not found

@Nakul93

### PR DESCRIPTION
**Pull request by SnoCold**
Fixes #300 

Added line to copy changes to pin_code_location_dtls

For People who have already run the script once, either start the process again or modify your existing json file

replace => pin_code_location_dtls: []
with => pin_code_location_dtls: [copy the location_dtls key value here]

### CODE REVIEW

**Comment by 6mxo89sqh** [comment]
@bombardier-gif Please revert this PR. This PR is causing to show location details twice:
#312 has fixed the issue and this isn't needed.
I have verified it.
```
	location_dtls:
+-------+-----------+--------------+
|   idx |   pincode |   alert_freq |
+=======+===========+==============+
|     1 |    825404 |          440 |
+-------+-----------+--------------+
	pin_code_location_dtls:
+-------+-----------+--------------+
|   idx |   pincode |   alert_freq |
+=======+===========+==============+
|     1 |    825404 |          440 |
+-------+-----------+--------------+
```

**Comment by SnoCold** [comment]
@6mxo89sqh  It is not the PR, but the JSON Objects are made such.. If you see the keys are different not the same.

**Comment by 6mxo89sqh** [comment]
@SnoCold in option 1 & 2, pin code details aren't needed. your pr was inserting that in option 1.

**Comment by SnoCold** [comment]
In option 1 especially pincode is needed.. that is the actual option.

**Pull request merged**
