### PR TITLE
Added feature to search for today and tomorrow

### PR DESCRIPTION
**Pull request by 6mxo89sqh**
For find by date, added feature to search for today and tomorrow.

I have tested once. 

plz test and share if it works fine in comments

### CODE REVIEW

**Comment by nolimits0007** [comment]
> For find by date, added feature to search for today and tomorrow.
> 
> I have tested once.
> 
> plz test and share if it works fine in comments

@6mxo89sqh so u did it . Will Chk & get back to u.

**Comment by nolimits0007** [comment]
@6mxo89sqh working like a charm for 15min no rate limit issues .
Screenshot 2021-06-06 at 12 53 47

But after 15min unable to send request for OTP.

Screenshot 2021-06-06 at 13 05 18

**Comment by shivaslifzz** [comment]
I have tested the code it's working fine 

notes:

1) This code is running for 15 mins window 
2) Supporting both today and tomorrow 
3) Use 9 secs if your using two districts 
4) Use 6/7 secs if your using single districts

**Comment by nolimits0007** [comment]
> I have tested the code it's working fine
> 
> notes:
> 
> 1. This code is running for 15 mins window
> 2. Supporting both today and tomorrow
> 3. Use 9 secs if your using two districts
> 4. Use 6/7 secs if your using single districts
> 
> @6mxo89sqh @bombardier-gif

@shivaslifzz as i was using 4 pin codes then i have to keep freq 9 sec . Let me test it .

**Comment by nolimits0007** [comment]
@6mxo89sqh @shivaslifzz @bombardier-gif i tested 40 min with 9 freq rate 4 pincodes working great.

Screenshot 2021-06-06 at 15 39 24


Screenshot 2021-06-06 at 15 41 58

**Comment by nolimits0007** [comment]
I have tested with 7 Freq & 4 pincodes 
Working Great. I think u guys can merge it.

**Comment by bombardier-gif** [comment]
Thanks merging it. @6mxo89sqh kudos for the effort.

**Pull request merged**
