### PR TITLE
More robust OTP search

### PR DESCRIPTION
**Pull request by ibrahim5253**
Make the search for OTP in SMS text agnostic to actual text. This
assumes OTP has length 6.

### CODE REVIEW

**Comment by bombardier-gif** [comment]
Thanks for the PR @ibrahim5253 
Have you observed issues with the OTP parsing in production?

**Comment by ibrahim5253** [comment]
No.

**Comment by bombardier-gif** [comment]
Thanks for the contribution :)
 Let us wait for sometime till the master gets a bit stable (We are getting huge issues in last few days).

**Comment by gitisuam** [comment]
@bombardier-gif -- Can you revert the script to the version where people were able to book slots ? May be that act as base version for new features.  I tried today for 400053 at 4pm it didnt work so the script is loosing its main objective. 
P.S - Hats off to you and other Python guys who are contributing to this project.

**Comment by gitisuam** [comment]
@darthfishious --- You are right I was able to book now at 6:04 lilavati. 
Few tricks: Put less than 3 pincodes and poll time more than 5 secs.

**Review by 6mxo89sqh — APPROVED** [review]

**Comment by 6mxo89sqh** [comment]
@ibrahim5253 Please resolve the conflicts.

**Comment by 6mxo89sqh** [comment]
no longer needed as #370 is merged.

**Pull request closed without merging**
