### PR TITLE
Updation of the KVdb instance

### PR DESCRIPTION
**Pull request by Spratiher9**
The Older KVdb instance expired so I am creating this pull request to replace the URI with the URI of the newer instance.

Old URI : https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/
New URI : https://kvdb.io/E8mUy1U35LegVxRyeiksog/

Thanks a lot, bombardier-gif.
Thanks to you I was able to book my slot.

### CODE REVIEW

**Comment by manasshukla1** [comment]
what is the use of this KVdb instance?

**Comment by Nakul93** [comment]
Is this a paid bucket? Plus there is already a PR for this issue

**Comment by manasshukla1** [comment]
Current script is giving me this error whenever it tries to book a slot:

**Input code incorrect
Input code incorrect
Input code incorrect**

**Comment by Nakul93** [comment]
> Current script is giving me this error whenever it tries to book a slot:
> 
> **Input code incorrect Input code incorrect Input code incorrect**
> @Spratiher9

I think this is not related to this PR. Your issue seems to be regarding captcha validation

**Comment by manasshukla1** [comment]
> > Current script is giving me this error whenever it tries to book a slot:
> > **Input code incorrect Input code incorrect Input code incorrect**
> > @Spratiher9
> 
> I think this is not related to this PR. Your issue seems to be regarding captcha validation

Yours is working fine? I am pissed off!

**Comment by Spratiher9** [comment]
@Nakul93 Yes it will be available for some time. The rooniks pull request I checked already and I think it will be convenient for the end user to create there own bucket and then pass that long string. 

@manasshukla1 You are entering something wrong. This pull request has no change other than the URI. So the error is not on my change.

**Comment by manasshukla1** [comment]
> @Nakul93 Yes it will be available for some time. The rooniks pull request I checked already and I think it will be convenient for the end user to create there own bucket and then pass that long string.
> 
> @manasshukla1 You are entering something wrong. This pull request has no change other than the URI. So the error is not on my change.

@Spratiher9 @Nakul93  Yes, the problem is not on your change. But I'm asking overall your scripts are working fine? You were able to book today?

**Comment by Nakul93** [comment]
One of my friend was able to book today so I think it’s working fine
@manasshukla1 could you please open up a separate issue and provide some screenshot of the logs

**Comment by Spratiher9** [comment]
Yeup I booked today only thanks to @bombardier-gif

**Comment by Spratiher9** [comment]
@Nakul93  Don't complete this pull request someone has deleted the bucket. I guess its better with the roonik's approach of self-servicing buckets

**Comment by Nakul93** [comment]
> @Nakul93 Don't complete this pull request someone has deleted the bucket. I guess its better with the roonik's approach of self-servicing buckets

ohh. I think you need to make it private as mentioned in roonik's PR.

**Comment by shailesh** [comment]
A better solution here #408

**Comment by 6mxo89sqh** [comment]
Closing this as we no longer provide kvdb instance. Going forward, user needs to provide.

**Pull request closed without merging**
