### PR TITLE
Help in release management

### PR DESCRIPTION
**Pull request by 6mxo89sqh**
On every PR Merge, release drafter will create a draft release with all change logs. 
After a few days or when you have confidence in your `main` branch, you can release the draft. On releasing, the action will upload exe & apk to that release.

This will help in #301 

@BlackRider97 @Nakul93 @bombardier-gif @shailesh If you are okay with this idea, i will update the README & complete the PR.

### CODE REVIEW

**Comment by 6mxo89sqh** [comment]
Sample release page is [here](https://github.com/6mxo89sqh/covid-vaccine-booking/releases/latest)

**Comment by Nakul93** [comment]
@6mxo89sqh one quick question, so only after a release, we would be able to pull the latest changes right?

**Comment by 6mxo89sqh** [comment]
@bombardier-gif this PR wasn't complete. It was in draft stage. Anyways, for this to work, you need to add your personal access token to Github secrets.

**Comment by 6mxo89sqh** [comment]
Go to Settings --> Secrets --> New repository secret --> Name: TOKEN --> Value: <personal access token> --> Add secret

**Comment by 6mxo89sqh** [comment]
> @6mxo89sqh one quick question, so only after a release, we would be able to pull the latest changes right?

No @Nakul93 , we need to update the read me asking users to use the latest release tag or download source from latest release.

**Comment by bombardier-gif** [comment]
How do I release the draft @6mxo89sqh ?

**Comment by 6mxo89sqh** [comment]
Go to [Release](https://github.com/bombardier-gif/covid-vaccine-booking/releases), there would be one draft (visible only to owner). Click on edit, then Click on Publish Release.

**Pull request merged**
