### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by abhibansal530**
Added a docker file. Makes it easier to run this script if you don't want to install python on your system (or you have older version).

### CODE REVIEW

**Comment by bombardier-gif** [comment]
Awesome! 
Thanks Abhi!

**Comment by bombardier-gif** [comment]
Can you also add steps to run it in the readme?

**Comment by shailesh** [comment]
This is cool though :)

**Review by Nakul93 — COMMENTED** [review]
Getting the following error while running the script in docker
`beep: Error: Could not open any device`
This script runs normally thereafter but not sure why the above error is coming up.

**Comment by abhibansal530** [comment]
> Can you also add steps to run it in the readme?

Done, PTAL.

**Comment by abhibansal530** [comment]
> Getting the following error while running the script in docker
> `beep: Error: Could not open any device`
> This script runs normally thereafter but not sure why the above error is coming up.

Yeah beep is not working inside docker somehow. Will try to fix this in another PR. Currently this should not be a deal-breaker I guess. I was able to book vaccine for 3 people using this image and didn't need beep.

**Comment by Nakul93** [comment]
> > Getting the following error while running the script in docker
> > `beep: Error: Could not open any device`
> > This script runs normally thereafter but not sure why the above error is coming up.
> 
> Yeah beep is not working inside docker somehow. Will try to fix this in another PR. Currently this should not be a deal-breaker I guess. I was able to book vaccine for 3 people using this image and didn't need beep.

Yeah I think thats fine

**Comment by Nakul93** [comment]
Where does the json file gets stored?

**Comment by abhibansal530** [comment]
> Where does the json file gets stored?

Good catch, thanks. I totally forgot about the json feature. Since this PR is merged, I'll create another one to add a persistent docker volume for storing json.

**Comment by 6mxo89sqh** [comment]
@abhibansal530 , i have covered it as part of #440 . You can review it. Also, the beep issue is also fixed.

**Pull request merged**
